name: idapt_dev
services:
  # Ollama is used as the LLM model provider for the backend.
  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    ports:
      - "11434:11434" # Allow access to ollama from outside for dev.
    networks:
      - idapt-backend-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: ["gpu"]
              count: all
    volumes:
      - ollama_data:/root/.ollama # Store the models in a volume so that we don't download them again at each rebuild
    restart: always
    runtime: nvidia

  # Postgres is used as the database for the backend.
  postgres:
    image: postgres:latest
    container_name: postgres
    build:
      context: ./postgres
      dockerfile: ./Dockerfile
    ports:
      - "5432:5432" # Allow access to the database from outside for dev.
    networks:
      - idapt-backend-network
    volumes:
      - postgres_data:/var/lib/postgresql/data # Store the database data in a volume so that we don't lose it at each rebuild
    env_file:
      - ./postgres/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h localhost || exit 1"]
      interval: 2s
      timeout: 5s
      retries: 20

  # The backend is the main service of the application.
  idapt-backend:
    build:
      context: ./backend
      dockerfile: dev.Dockerfile 
    container_name: idapt-backend
    ports:
      - "8000:8000" # Allow access to the backend from outside for dev.
    networks:
      - idapt-backend-network
      - idapt-frontend-network
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./postgres/.env # Used to get the default superuser password and other variables.
      - ./backend/.env
      - ./dev.env # To pass the dev variable.
    volumes:
      - ./backend:/backend # Use a bind mount to sync the backend code with the container and allow code changes to be synced.
      - idapt_data:/idapt_data # The volume where the data is stored.
      
  # Use a node container to develop the frontend application.
  idapt-frontend:
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    container_name: idapt-frontend
    expose:
      - "3000"
    networks:
      - idapt-frontend-network
    env_file:
      - ./frontend/.env
      - ./dev.env # To pass the dev variable.
    volumes:
      - ./frontend:/frontend # Use a bind mount to sync the frontend code with the container and allow code changes to be synced.

  # Use a separate container to use nginx to do like in the production environment.
  # ? Dont use nginx in dev ? Just expose every container on host ports ?
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "3030:3030"
    volumes:
      - ./frontend/nginx.dev.conf:/etc/nginx/nginx.conf:ro
    networks:
      - idapt-frontend-network
    depends_on:
      - idapt-frontend
      - idapt-backend

volumes:
  postgres_data:
  ollama_data:
  idapt_data:

networks:
  idapt-backend-network:
    attachable: false
    name: idapt-backend-network
    driver: bridge # Change to not allow external access later ?
  idapt-frontend-network:
    attachable: true
    name: idapt-frontend-network
    driver: bridge
