name: idapt_dev

services:

  # The backend is the main service of the application.
  idapt-backend:
    build:
      context: ./backend
      dockerfile: dev.Dockerfile 
    container_name: idapt-backend
    expose:
      - "8000"
    networks:
      idapt-backend-external-network: {}
      idapt-backend-network: {}
    # Expose the host.docker.internal so that we can access ollama runnning on the localost from the container.
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 1s
      timeout: 5s
      retries: 30
    environment:
      ENVIRONMENT: dev
      HOST_DOMAIN: ${HOST_DOMAIN}
    volumes:
      - ./backend:/backend # Use a bind mount to sync the backend code with the container and allow code changes to be synced.
      - ./user_data:/data # The volume where the data is stored. Use data mount name to make it shorter.
    restart: unless-stopped
    # Container security hardening
    security_opt:
      - no-new-privileges:true
    #cap_drop: # TODO
    #  - ALL

  idapt-frontend:
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    container_name: idapt-frontend
    expose:
      - "3000"
    networks:
      idapt-frontend-external-network: {}
      idapt-frontend-network: {}
    #depends_on:     # Disable for dev to have a faster startup time, backend will simply not respond at frontend start.
      #idapt-backend:
      #  condition: service_healthy
    environment:
      ENVIRONMENT: dev
      NEXT_TELEMETRY_DISABLED: 1
    volumes:
      - ./frontend:/frontend # Use a bind mount to sync the frontend code with the container and allow code changes to be synced.
    restart: unless-stopped
    # Container security hardening
    user: node
    security_opt:
      - no-new-privileges:true
    #cap_drop: # TODO
    #  - ALL

# Nginx to manage every communication between containers and outside world.
  idapt-nginx:
    container_name: idapt-nginx
    build:
      context: ./nginx
      dockerfile: ./dev.Dockerfile
    environment:
      ENVIRONMENT: dev
      # Entrypoint script variables
      HOST_DOMAIN: ${HOST_DOMAIN}
      # Container variables
      CERTBOT_EMAIL: ${CERTBOT_EMAIL}
    ports:
      # Expose the nginx listening ports through the host firewall.
      # Add 127.0.0.1 to only open ports locally and not through the host firewall.
      - '80:80/tcp'
      - '443:443/tcp'
      - '443:443/udp'
    # Nginx has access to every container exposed via their own network for routing.
    networks:
      idapt-nginx-external-network: {}
      idapt-frontend-network: {}
      idapt-backend-network: {}
    volumes:
      - nginx_data:/etc/letsencrypt
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 1s
      timeout: 5s
      retries: 30
    restart: unless-stopped
    # Container security hardening
    security_opt:
      - no-new-privileges:true
    #cap_drop: # TODO
    #  - ALL
    #cap_add:
    #  - NET_BIND_SERVICE  # Only for nginx

volumes:
  nginx_data:

# One network for each service to keep them isolated.
networks:
  # Dedicated external networks for services that need internet access
  idapt-nginx-external-network:
    attachable: false
    name: idapt-nginx-external-network
    driver: bridge
  idapt-frontend-external-network:
    attachable: false
    name: idapt-frontend-external-network
    driver: bridge
  idapt-backend-external-network:
    attachable: false
    name: idapt-backend-external-network
    driver: bridge
  # Internal networks for inter container communication.
  idapt-backend-network:
    internal: true
    attachable: false
    name: idapt-backend-network
    driver: bridge
  idapt-frontend-network:
    internal: true
    attachable: false
    name: idapt-frontend-network
    driver: bridge