version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

  idaptServer:
    build: .
    container_name: idaptServer
    ports:
      - "4231:4231" # TODO make this use app port ?
    env_file:
      - .env  # This will load the environment variables from your .env file
    environment:
      DATABASE_URL: ${DATABASE_URL}
      #TODO add other variables ?

volumes:
  postgres_data:
