# Use the official Node.js image as the base image
FROM node:16

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

# Build the Next.js application
RUN npm run build

# Push the Prisma schema to the database
RUN npx prisma db push

# Expose the port the app runs on inside the container
EXPOSE 4231

# Command to run the application
CMD ["npm", "start"]