name: idapt
services:

  # Integrated Ollama instance
  idapt-ollama:
    container_name: idapt-ollama
    image: ollama/ollama:latest
    expose:
      - "11434"
    networks:
      idapt-ollama-external-network: {}
      idapt-ollama-network: {}
    runtime: nvidia # Remove this if you don't want to use GPU for ollama.
    deploy: # Remove this if you don't want to use GPU for ollama.
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: ["gpu"]
              count: all
    healthcheck:
      test: ["CMD", "ollama", "--version"]  # Check if Ollama is responding
      interval: 1s
      timeout: 5s
      retries: 30
    volumes:
      - ollama_data:/root/.ollama # Store the models in a volume so that we don't download them again at each rebuild
    restart: always
    # Container security hardening
    security_opt:
      - no-new-privileges:true
    #cap_drop: # TODO
    #  - ALL




  # The backend is the main service of the application.
  idapt-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile 
    container_name: idapt-backend
    expose:
      - "8000"
    networks:
      idapt-backend-external-network: {}
      idapt-backend-network: {}
      idapt-ollama-network: {}
    depends_on:
      idapt-ollama:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 1s
      timeout: 5s
      retries: 30
    environment:
      ENVIRONMENT: prod
      HOST_DOMAIN: ${HOST_DOMAIN}
    env_file:
      - ./backend/.env
    volumes:
      - backend_data:/backend_data # The volume where the app data is stored.
      - idapt_data:/data # The volume where the data is stored. Use data mount name to make it shorter.
    restart: always
    # Container security hardening
    security_opt:
      - no-new-privileges:true
    #cap_drop: # TODO
    #  - ALL



# Nginx to manage every communication between containers and outside world.
  idapt-nginx:
    container_name: idapt-nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    environment:
      # Frontend variables
      ENVIRONMENT: prod
      NEXT_PUBLIC_HOST_DOMAIN: ${HOST_DOMAIN}
      # Entrypoint script variables
      HOST_DOMAIN: ${HOST_DOMAIN}
      # Container variables
      CERTBOT_EMAIL: ${CERTBOT_EMAIL}
      # Optional (Defaults)
      DHPARAM_SIZE: 2048
      ELLIPTIC_CURVE: secp256r1
      RENEWAL_INTERVAL: 8d
      RSA_KEY_SIZE: 2048
      STAGING: 0
      USE_ECDSA: 1
      # Advanced (Defaults)
      CERTBOT_AUTHENTICATOR: webroot
      CERTBOT_DNS_PROPAGATION_SECONDS: ""
      DEBUG: 0
      USE_LOCAL_CA: 0
    env_file:
      - ./frontend/.env
    ports:
      # Expose the nginx listening ports through the host firewall.
      # Add 127.0.0.1 to only open ports locally and not through the host firewall.
      - '80:80/tcp'
      - '443:443/tcp'
      - '443:443/udp'
    # Nginx has access to every container exposed via their own network for routing.
    networks:
      idapt-nginx-external-network: {}
      idapt-backend-network: {}
    volumes:
      - nginx_letsencrypt:/etc/letsencrypt # Persist the certificates.
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 1s
      timeout: 5s
      retries: 30
    restart: always
    # Container security hardening
    security_opt:
      - no-new-privileges:true
    #cap_drop: # TODO
    #  - ALL
    #cap_add:
    #  - NET_BIND_SERVICE  # Only for nginx




volumes:
  backend_data:
  idapt_data:
  ollama_data: # TODO use a shared read only volume for ollama models to not have duplicates for each pod.
  nginx_letsencrypt:

# One network for each service to keep them isolated.
networks:
  # Dedicated external networks for services that need internet access
  idapt-nginx-external-network:
    attachable: false
    name: idapt-nginx-external-network
    driver: bridge
  idapt-backend-external-network:
    attachable: false
    name: idapt-backend-external-network
    driver: bridge
  idapt-ollama-external-network:
    attachable: false
    name: idapt-ollama-external-network
    driver: bridge
  # Internal networks for inter container communication.
  idapt-backend-network:
    internal: true
    attachable: false
    name: idapt-backend-network
    driver: bridge
  idapt-ollama-network:
    internal: true
    attachable: false
    name: idapt-ollama-network
    driver: bridge