version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}

  idaptServer:
    build: .
    container_name: idaptServer
    ports:
      - "4231:4231" # TODO make this use app port ?
    env_file:
      - .env  # This will load the environment variables from your .env file
    environment:
      MONGODB_URI: ${MONGODB_URI}
      #TODO add other variables ?

volumes:
  mongo_data: