services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432" # TODO remove for production as this is only for dev access to the database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PGUSER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  idapt-backend:
    image: python:3.11-slim
    container_name: idapt-backend
    ports:
      - "8000:8000"
    env_file:
      - master.env
      - ./backend/.env
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/backend
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  idapt-frontend:
    image: node:20-alpine
    container_name: idapt-frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    depends_on:
      idapt-backend:
        condition: service_healthy
    volumes:
      - ./frontend:/frontend

  ollama:
    container_name: ollama
    image: ollama/ollama:latest
      - "5432:5432" # Allow access to ollama from outside if the user wants to. # TODO remove for production ?
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: ["gpu"]
              count: all
    volumes:
      - /usr/share/ollama/.ollama:/root/.ollama  # Mount the host directory so that we use existing models and dont download them again at each rebuild # TODO adjust for windows and macos.
    restart: always
    runtime: nvidia

volumes:
  postgres_data: