name: idapt

services:

# Nginx to manage app access and serve static frontend.
  idapt-nginx:
    container_name: idapt-nginx
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    environment:
      ENVIRONMENT: prod
      DEPLOYMENT_TYPE: hosted
      HOST_DOMAIN: ${HOST_DOMAIN}
    # Nginx has access to every container exposed via their own network for routing.
    volumes:
      - certs:/etc/letsencrypt
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 1s
      timeout: 5s
      retries: 30
    restart: unless-stopped
    network_mode: host
    # Container security hardening
    security_opt:
      - no-new-privileges:true
    #cap_drop: # TODO
    #  - ALL
    #cap_add:
    #  - NET_BIND_SERVICE  # Only for nginx

volumes:
  certs: