"""add per datasource embeddings settings

Revision ID: ca0e86b3ebd4
Revises: 8c658306a266
Create Date: 2025-01-19 10:31:22.525963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca0e86b3ebd4'
down_revision: Union[str, None] = '8c658306a266'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasources', sa.Column('embedding_provider', sa.String(), nullable=False))
    op.add_column('datasources', sa.Column('embedding_settings', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datasources', 'embedding_settings')
    op.drop_column('datasources', 'embedding_provider')
    # ### end Alembic commands ###
