"""add processing stack supported file extensions

Revision ID: 8c658306a266
Revises: 3083d9e553d3
Create Date: 2025-01-18 22:27:04.951718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c658306a266'
down_revision: Union[str, None] = '3083d9e553d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processing_stacks', sa.Column('supported_extensions', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('processing_stacks', 'supported_extensions')
    # ### end Alembic commands ###
