"""Init db

Revision ID: b07a20202991
Revises: 
Create Date: 2025-02-02 12:22:55.545708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b07a20202991'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('identifier', sa.String(), nullable=False),
    sa.Column('schema_identifier', sa.String(), nullable=False),
    sa.Column('setting_schema_json', sa.JSON(), nullable=False),
    sa.Column('value_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('identifier')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    # ### end Alembic commands ###
