apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: idapt-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - localhost
    secretName: idapt-tls
  rules:
  - host: localhost
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: idapt-backend
            port:
              number: 8000