apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: idapt-cert-dev
spec:
  secretName: idapt-tls
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  subject:
    organizations:
    - idapt
  commonName: localhost
  dnsNames:
  - localhost
  - idapt.local
  issuerRef:
    name: idapt-ca-issuer
    kind: ClusterIssuer 