apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: idapt-backend
spec:
  serviceName: idapt-backend
  replicas: 3
  selector:
    matchLabels:
      app-name: idapt-backend
  template:
    metadata:
      labels:
        app-name: idapt-backend
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app-name
                  operator: In
                  values:
                  - idapt-backend
              topologyKey: kubernetes.io/hostname
      containers:
        - name: idapt-backend
          image: ghcr.io/idapt/idapt:backend-main
          imagePullPolicy: Always
          ports:
            - containerPort: 9004
          env:
            - name: ENVIRONMENT
              value: "dev"
            - name: DEPLOYMENT_TYPE
              value: "hosted"
            - name: HOST_DOMAIN
              value: "localhost"
            - name: API_PORT
              value: "9004"
            - name: ANONYMIZED_TELEMETRY
              value: "False"
            - name: MAX_PUBLIC_USERS_FOR_THIS_HOST
              value: "100"
          livenessProbe:
            httpGet:
              #httpHeaders:
              #  - name: Host
              #    value: localhost
              #insecureSkipVerify: true  # Bypass cert validation for self-signed dev cert
              path: /api/health
              port: 9004
              scheme: HTTPS
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
      restartPolicy: Always
      volumes: [] # User data volumes will be mounted by the pod itself