"""add file_id to embeddings

Revision ID: 229dcd101018
Revises: 
Create Date: 2024-11-01 20:45:08.898981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '229dcd101018'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('data_docstore', 'value',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False)
    op.drop_index('data_docstore:idx_key_namespace', table_name='data_docstore')
    op.drop_constraint('data_docstore:unique_key_namespace', 'data_docstore', type_='unique')
    op.add_column('data_embeddings', sa.Column('file_id', sa.Integer(), nullable=True))
    op.alter_column('data_embeddings', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.create_foreign_key(None, 'data_embeddings', 'files', ['file_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'data_embeddings', type_='foreignkey')
    op.alter_column('data_embeddings', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('data_embeddings', 'file_id')
    op.create_unique_constraint('data_docstore:unique_key_namespace', 'data_docstore', ['key', 'namespace'])
    op.create_index('data_docstore:idx_key_namespace', 'data_docstore', ['key', 'namespace'], unique=False)
    op.alter_column('data_docstore', 'value',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###
