name: Build and publish backend docker image on commit push to ghcr.io/idapt/idapt-backend:latest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
        
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}    
        password: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Build the Docker image
      run: docker build backend --tag idapt-backend:main && docker run ghcr.io/idapt/idapt-backend:main && docker push ghcr.io/idapt/idapt-backend:main
